oc_bigbrother:
    resource: "@OCBigbrotherBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

oc_platform_dev:
    resource: "@OCPlatformBundle/Resources/config/routing_dev.yml"
    prefix:   /
